read_excel('C:/Users/pnkid/Documents/apprate.xlsx')
polldata <- read_excel('C:/Users/pnkid/Documents/apprate.xlsx')
nostraddle <- subset(polldata, { as.Date(startdate) >= as.Date("2018-11-17") & as.Date(enddate) < as.Date("2018-12-22") } | (as.Date(startdate) >= as.Date("2018-12-22") & as.Date(enddate) <= as.Date("2019-01-25")) | as.Date(startdate) > as.Date("2019-01-25"))
state_nostraddle = within(nostraddle, { period = ifelse(as.Date(enddate) < as.Date("2018-12-22"), 0, ifelse(as.Date(enddate) >= as.Date("2018-12-22") & as.Date(enddate) <= as.Date("2019-1-25"), 1, 2)) })
before_after <- subset(state_nostraddle, period == 0 | period == 2)
during_after <- subset(state_nostraddle, period == 1 | period == 2)
before_during_app_model <- lm(approve ~ period, before_during)
before_after_app_model <- lm(approve ~ period, before_after)
during_after_app_model <- lm(approve ~ period, during_after)