library("readxl")
polldata <- read_excel("poll_and_avg.xlsx")
nostraddle <- subset(polldata, { as.Date(startdate) >= as.Date("2018-11-17") & as.Date(enddate) < as.Date("2018-12-22") } | (as.Date(startdate) >= as.Date("2018-12-22") & as.Date(enddate) <= as.Date("2019-01-25")) | as.Date(startdate) > as.Date("2019-01-25"))
state_nostraddle = within(nostraddle, { period = ifelse(as.Date(enddate) < as.Date("2018-12-22"), 0, ifelse(as.Date(enddate) >= as.Date("2018-12-22") & as.Date(enddate) <= as.Date("2019-1-25"), 1, 2)) })
before_during <- subset(state_nostraddle, period == 0 | period == 1)
before_after <- subset(state_nostraddle, period == 0 | period == 2)
during_after <- subset(state_nostraddle, period == 1 | period == 2)
before_during_app_model <- lm(disapprove ~ period, before_during)
before_after_app_model <- lm(disapprove ~ period, before_after)
during_after_app_model <- lm(disapprove ~ period, during_after)
before_during_app_model_dji <- lm(disapprove ~ period + djavg, before_during)
before_after_app_model_dji <- lm(disapprove ~ period + djavg, before_after)
during_after_app_model_dji <- lm(disapprove ~ period + djavg, during_after)
before_during_app_model_ru <- lm(disapprove ~ period + ruavg, before_during)
before_after_app_model_ru <- lm(disapprove ~ period + ruavg, before_after)
during_after_app_model_ru <- lm(disapprove ~ period + ruavg, during_after)